% Set the parameters below and run the script to make plots from the
% CSV files generated by the EM Fiber Clustering Module in Slicer3.
% Mahnaz Maddah, Sept. 2009.

%%%%% parameters
params.fileDir = 'D:/Mahnaz/Projects/Clustering/Training/Data/';                % location where CSV files are stored
params.filePrefix = 'feature';                                                  % files' prefix
params.clusterIds = 1:2;                                                        % cluster Ids for which plots need to be generated

%%%%% main function
makePlotsFromCVSfiles(params)
%%%%%